name: Mirror and push

on: 
  workflow_dispatch:
  schedule:
    - cron:  '45 11 * * 3'
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
     
    - name: Install requests
      run: pip install requests
 
    - name: Update paper list
      run: python dl.py
        
    - name: Output for windows
      uses: actions/upload-artifact@v2
      with:
        name: dl
        path: output/scratch-win.exe
        retention-days: 14

    - name: Output for macos
      uses: actions/upload-artifact@v2
      with:
        name: dl
        path: output/scratch-mac.exe
        retention-days: 14
